### ISSUE TITLE
Unable to migrate taiga-back

### ISSUE THREAD

**Issue by christianlupus** [docker-taiga/back#12]
I have the problem, that I had a comparably old installation running on commit `dd69e3b36dbf71cd90211dde052a0f3b7a920c93`. I wanted to update to the most recent version now.

The backend causes problems during the migration phase: I uploaded the logs as [gist](https://gist.github.com/christianlupus/fb8ff3f0b794013fe73859fa5eee29bd).

I also opened an issue on the [main taiga back repository](https://github.com/taigaio/taiga-back/issues/1429#event-3308720296). They called docker not supported and refused to help.

Can you tell me what problem is causing the problem or how I can further debug the issue?

**Comment by christianlupus** [comment]
I think I found the reason for the problem. The file `/taiga-conf/celery.py` in the docker container was not present. This was due to the fact that the folder `/taiga-conf` is a mounted volume. I had it pre-initialized from the older container. Thus the `celery.py` was not in it. Putting it manually there seems to have solved the problem.

Nevertheless, I am asking myself: Why are you putting this file in the volume? The approach in your start script with `sed` is not too expensive to do it regularly on every startup. If you want me to file a PR, please tell me.

**Comment by w1ck3dg0ph3r** [comment]
Hi!

The reason It is put into volume is so that users can customize the config files themselves and keep their changes while upgrading/restarting images. Otherwise we would need to maintain an exhaustive list of config options in env vars (which is, given there are plugins involved, looks impossible to me). The other option would be a system to distinguish the changes made by the user and the ones made by the image, which would not be trivial, I imagine.

I definitely should, though, keep a changelog with an upgrade instructions when something major is changed, so, sorry about the inconvinience. Alas, I have miniscule amount of time to spend on this right now.

**Comment by christianlupus** [comment]
I was not thinking of putting the config file in the container. I understand this is most probably better put into a persistent storage.

I was merely referring to the `celery.py` script that was patched by you to reflect/allow the variable substitution. Or are you expecting people to have made changes at this file as well?

**Comment by w1ck3dg0ph3r** [comment]
> Or are you expecting people to have made changes at this file as well?

Well, yes I do view it as a config file. There are less reasons for user to customize it, I suppose, but still I'm not comfortable obscuring it away.
